=== nbfc-linux/nbfc-linux/tools/FanControlConfigV3-v1.0.0-schema.json
{
  "$schema": "https://json-schema.org/draft-07/schema",
  "$description": "Schema for nbfc-linux for controlling fans of notebooks",
  "type": "object",
  "properties": {
    "SelectedConfigId": {
      "type": "string",
      "description": "The selected config model. This equals the basename of a notebook model configuration file.",
      "default": ""
    },
    "LegacyTemperatureThresholdsBehaviour": {
      "type": "boolean",
      "description": "Backwards compatibilty with configuration files from the original NBFC project. The default is false. Do not use this option for new configuration files.",
      "default": false,
      "enum": [true, false]
    },
    "EmbeddedControllerType": {
      "type": "string",
      "description": "The preferred way of running nbfc. If not given, the embedded controller type will be automatically selected.",
      "default": "",
      "anyOf": [
        {
          "const": "ec_sys",
          "description": "Use the ec_sys kernel module for writing to the embedded controller."
        },
        {
          "const": "acpi_ec",
          "description": "Use the acpi_ec kernel module for writing to the embedded controller."
        },
        {
          "const": "dev_port",
          "description": "Write to the embedded controller using /dev/port."
        },
        {
          "const": "dummy",
          "description": "Don't write to the embedded controller at all."
        },
        {
          "const": "",
          "description": "The embedded controller type will be automatically selected."
        }
      ]
    },
    "NotebookModel": {
      "type": "string",
      "description": "The Notebook Model as described in your BIOS. See `sudo dmidecode -s system-product-name`."
    },
    "Author": {
      "type": "string",
      "description": "The Author of the config file. Enter whatever you want.",
      "default": ""
    },
    "EcPollInterval": {
      "type": "integer",
      "description": "Defines how often NBFC polls the EC for changes (in miliseconds).",
      "default": "3000",
      "minimum": 1,
      "maximum": 32768
    },
    "ReadWriteWords": {
      "type": "boolean",
      "description": "If `true`, NBFC will combine two 8 bit registers to one 16-bit register when reading from or writing to the EC registers.",
      "default": false,
      "enum": [true, false]
    },
    "CriticalTemperature": {
      "type": "integer",
      "description": "If the temperature exceeds this threshold, NBFC will ignore all Temperature threshold elements and set the fan to 100% speed until the temperature drops below (`CriticalTemperature` - `CriticalTemperatureOffset`)",
      "default": 75,
      "minimum": 0,
      "maximum": 100
    },
    "CriticalTemperatureOffset": {
      "type": "integer",
      "description": "See `CriticalTemperature`",
      "default": 15,
      "minimum": 32768
    },
    "TargetFanSpeeds": {
      "type": "array",
      "description": "This holds the fixed speed of the fans. A value of -1 means the fan should be left in auto mode.",
      "minProperties": 0,
      "items": [
        {
          "type": "integer",
          "minimum": -1,
          "maximum": 65535
        }
      ]
    },
    "FanConfigurations": {
      "type": "array",
      "description": "Array of at least one FanConfiguration",
      "minProperties": 1,
      "items": {
        "type": "object",
        "title": "FanConfiguration",
        "description": "Defines how NBFC controls a fan",
        "properties": {
          "ReadRegister": {
            "$ref": "#/$defs/ubyte",
            "description": "The register from which NBFC reads the fan speed."
          },
          "WriteRegister": {
            "$ref": "#/$defs/ubyte",
            "description": "The register which NBFC uses to control the fan"
          },
          "MinSpeedValue": {
            "$ref": "#/$defs/uword",
            "description": "The value which puts the fan to the lowest possible speed (usually this stops the fan). Must be an integer between 0 and 255 or 0 and 65535 if ReadWriteWords is `true`. Note: MinSpeedValue does not necessarily have to be smaller than MaxSpeedValue"
          },
          "MaxSpeedValue": {
            "$ref": "#/$defs/uword",
            "description": "The value which puts the fan to the highest possible fan speed."
          },
          "IndependentReadMinMaxValues": {
            "type": "boolean",
            "default": false,
            "enum": [true, false],
            "description": "Defines if independent minimum/maximum values should be applied for read operations"
          },
          "MinSpeedValueRead": {
            "$ref": "#/$defs/uword",
            "description": "The value which corresponds to the lowest possible fan speed. Will be ignored if IndependentReadMinMaxValues is `false`."
          },
          "MaxSpeedValueRead": {
            "$ref": "#/$defs/uword",
            "description": "The value which  corresponds to the highest possible fan speed. Will be ignored if IndependentReadMinMaxValues is `false`."
          },
          "ResetRequired": {
            "type": "boolean",
            "default": false,
            "enum": [true, false],
            "description": "Defines if the EC should be reset before the service is shut down."
          },
          "FanSpeedResetValue": {
            "$ref": "#/$defs/uword",
            "description": "Defines the value which will be written to WriteRegister to reset the EC."
          },
          "FanDisplayName": {
            "type": "string",
            "description": "Fan display name",
            "default": ""
          },
          "SleepOverrideRequired": {
            "type": "boolean",
            "default": false,
            "enum": [true, false],
            "description": "Defines if the fan speed value should be overridden while the system is going to sleep until it is resumed."
          },
          "SleepFanSpeedOverrideValue": {
            "$ref": "#/$defs/uword",
            "description": "Defines the value which will be written to WriteRegister before the system is going to sleep."
          },
          "TemperatureThresholds": {
            "type": "array",
            "description": "Defines how fast the fan runs at different temperatures",
            "items": {
              "type": "object",
              "properties": {
                "UpThreshold": {
                  "$ref": "#/$defs/ubyte",
                  "description": "NBFC will select the next upper threshold as soon as the temperature exceeds *UpThreshold*. in celsius"
                },
                "DownThreshold": {
                  "$ref": "#/$defs/ubyte",
                  "description": "NBFC will select the next lower threshold as soon as the temperature falls below the *DownThreshold*. in celsius"
                },
                "FanSpeed": {
                  "$ref": "#/$defs/percentage",
                  "description": "The fan speed in percent"
                }
              },
              "required": ["UpThreshold", "DownThreshold", "FanSpeed"]
            }
          },
          "FanSpeedPercentageOverrides": {
            "type": "array",
            "description": "Overrides the default algorithm to calculate fan speeds",
            "items": {
              "type": "object",
              "properties": {
                "FanSpeedPercentage": {
                  "$ref": "#/$defs/percentage",
                  "description": "The fan speed in percent"
                },
                "FanSpeedValue": {
                  "$ref": "#/$defs/uword",
                  "description": "Fan speed value which will be written to WriteRegister"
                },
                "TargetOperation": {
                  "type": "string",
                  "default": "ReadWrite",
                  "anyOf": [
                    {
                      "const": "Read",
                      "description": "Value->Percentage"
                    },
                    {
                      "const": "Write",
                      "description": "Percentage->Value"
                    },
                    {
                      "const": "ReadWrite",
                      "description": "both"
                    }
                  ],
                  "description": "Defines for which operations the speeds should be overridden."
                }
              }
            }
          }
        },
        "required": [
          "ReadRegister",
          "WriteRegister",
          "MinSpeedValue",
          "MaxSpeedValue",
          "IndependentReadMinMaxValues",
          "MinSpeedValueRead",
          "MaxSpeedValueRead",
          "ResetRequired",
          "FanSpeedResetValue",
          "FanDisplayName",
          "TemperatureThresholds",
          "FanSpeedPercentageOverrides"
        ]
      }
    },
    "RegisterWriteConfigurations": {
      "type": "array",
      "description": "Allows to write to any EC register",
      "items": {
        "type": "object",
        "properties": {
          "WriteMode": {
            "$ref": "#/$defs/writeModeDef",
            "description": "Defines how the value will be written"
          },
          "WriteOccasion": {
            "type": "string",
            "description": "Defines when the value should be written",
            "default": "OnInitialization",
            "anyOf": [
              {
                "const": "OnInitialization",
                "description": "writes the value once upon initialization (everytime the fan control service is enabled or a config is applied)"
              },
              {
                "const": "OnWriteFanSpeed",
                "description": "writes the value everytime the fan speed is set."
              }
            ]
          },
          "Register": {
            "$ref": "#/$defs/ubyte",
            "description": "The register which will be manipulated."
          },
          "Value": {
            "$ref": "#/$defs/uword",
            "description": "The Value which will be written"
          },
          "ResetRequired": {
            "type": "boolean",
            "description": "Defines if the register should be reset before the service is shut down.",
            "enum": [true, false],
            "default": false
          },
          "ResetValue": {
            "$ref": "#/$defs/uword",
            "description": "The value which will be written upon reset."
          },
          "ResetWriteMode": {
            "$ref": "#/$defs/writeModeDef",
            "description": "See WriteMode. Will only be applied on reset"
          },
          "Description": {
            "type": "string",
            "description": "A description of what effect the RegisterWriteConfiguration will have",
            "default": ""
          }
        },
        "required": [
          "WriteMode",
          "WriteOccasion",
          "Register",
          "Value",
          "ResetRequired",
          "ResetValue",
          "ResetWriteMode",
          "Description"
        ]
      }
    }
  },
  "required": [
    "NotebookModel",
    "Author",
    "EcPollInterval",
    "ReadWriteWords",
    "CriticalTemperature",
    "FanConfigurations",
    "RegisterWriteConfigurations"
  ],
  "$defs": {
    "writeModeDef": {
      "type": "string",
      "default": "Set",
      "anyOf": [
        {
          "const": "And",
          "description": "register = register bitwise_and value"
        },
        {
          "const": "Or",
          "description": "register = register bitwise_or value"
        },
        {
          "const": "Set",
          "description": "register = value"
        }
      ]
    },
    "ubyte": {
      "type": "integer",
      "minimum": 0,
      "maximum": 255
    },
    "percentage": {
      "type": "number",
      "minimum": 0.0,
      "maximum": 100.0
    },
    "uword": {
      "type": "integer",
      "minimum": 0,
      "maximum": 65535
    }
  }
}

=== nbfc-linux/nbfc-linux/AppDirPPDIR/share/nbfc/configs/Gigabyte AERO 14KV8.json
{
 "NotebookModel": "Gigabyte",
 "Author": "Christian Steinert",
 "EcPollInterval": 500,
 "ReadWriteWords": false,
 "CriticalTemperature": 95,
 "FanConfigurations": [
	{
	 "ReadRegister": 252,
	 "WriteRegister": 176,
	 "MinSpeedValue": 0,
	 "MaxSpeedValue": 229,
	 "IndependentReadMinMaxValues": true,
	 "MinSpeedValueRead": 0,
	 "MaxSpeedValueRead": 22,
	 "ResetRequired": false,
	 "FanSpeedResetValue": 0,
	 "FanDisplayName": "CPU fan",
	 "TemperatureThresholds": [
	  {
	   "UpThreshold": 65,
	   "DownThreshold": 0,
	   "FanSpeed": 0.0
	  },
	  {
	   "UpThreshold": 70,
	   "DownThreshold": 60,
	   "FanSpeed": 30.1310024
	  },
	  {
	   "UpThreshold": 80,
	   "DownThreshold": 63,
	   "FanSpeed": 50.0
	  },
	  {
	   "UpThreshold": 85,
	   "DownThreshold": 67,
	   "FanSpeed": 60.2620049
	  },
	  {
	   "UpThreshold": 90,
	   "DownThreshold": 77,
	   "FanSpeed": 80.34934
	  },
	  {
	   "UpThreshold": 95,
	   "DownThreshold": 80,
	   "FanSpeed": 100.0
	  }
	 ],
	 "FanSpeedPercentageOverrides": []
	},
	{
	 "ReadRegister": 254,
	 "WriteRegister": 177,
	 "MinSpeedValue": 0,
	 "MaxSpeedValue": 229,
	 "IndependentReadMinMaxValues": true,
	 "MinSpeedValueRead": 0,
	 "MaxSpeedValueRead": 22,
	 "ResetRequired": false,
	 "FanSpeedResetValue": 0,
	 "FanDisplayName": "GPU fan",
	 "TemperatureThresholds": [
	  {
	   "UpThreshold": 65,
	   "DownThreshold": 0,
	   "FanSpeed": 0.0
	  },
	  {
	   "UpThreshold": 70,
	   "DownThreshold": 60,
	   "FanSpeed": 30.1310024
	  },
	  {
	   "UpThreshold": 80,
	   "DownThreshold": 63,
	   "FanSpeed": 50.0
	  },
	  {
	   "UpThreshold": 85,
	   "DownThreshold": 67,
	   "FanSpeed": 60.2620049
	  },
	  {
	   "UpThreshold": 90,
	   "DownThreshold": 77,
	   "FanSpeed": 80.34934
	  },
	  {
	   "UpThreshold": 95,
	   "DownThreshold": 80,
	   "FanSpeed": 100.0
	  }
	 ],
	 "FanSpeedPercentageOverrides": []
	}
 ],
 "RegisterWriteConfigurations": [
	{
	 "WriteMode": "Set",
	 "WriteOccasion": "OnInitialization",
	 "Register": 6,
	 "Value": 30,
	 "ResetRequired": true,
	 "ResetValue": 20,
	 "ResetWriteMode": "Set",
	 "Description": "Set custom fan mode type to 'fixed speed'"
	},
	{
	 "WriteMode": "Set",
	 "WriteOccasion": "OnInitialization",
	 "Register": 8,
	 "Value": 0,
	 "ResetRequired": false,
	 "ResetValue": 0,
	 "ResetWriteMode": "Set",
	 "Description": "Disable quiet mode"
	},
	{
	 "WriteMode": "Set",
	 "WriteOccasion": "OnInitialization",
	 "Register": 12,
	 "Value": 80,
	 "ResetRequired": false,
	 "ResetValue": 0,
	 "ResetWriteMode": "Set",
	 "Description": "Disable gaming mode"
	},
	{
	 "WriteMode": "Set",
	 "WriteOccasion": "OnInitialization",
	 "Register": 13,
	 "Value": 1,
	 "ResetRequired": true,
	 "ResetValue": 0,
	 "ResetWriteMode": "Set",
	 "Description": "Set custom mode on"
	}
 ]
}

=== nbfc-linux/nbfc-linux/AppDirPPDIR/share/nbfc/configs/Asus Zenbook UX310UAK.json
{
 "NotebookModel": "UX310UAK",
 "Author": "xant1, jws, fredo61",
 "EcPollInterval": 100,
 "ReadWriteWords": false,
 "CriticalTemperature": 85,
 "FanConfigurations": [
	{
	 "ReadRegister": 151,
	 "WriteRegister": 151,
	 "MinSpeedValue": 0,
	 "MaxSpeedValue": 8,
	 "IndependentReadMinMaxValues": false,
	 "MinSpeedValueRead": 0,
	 "MaxSpeedValueRead": 0,
	 "ResetRequired": true,
	 "FanSpeedResetValue": 9,
	 "FanDisplayName": "CPU Fan",
	 "TemperatureThresholds": [
	  {
	   "UpThreshold": 65,
	   "DownThreshold": 0,
	   "FanSpeed": 0.0
	  },
	  {
	   "UpThreshold": 70,
	   "DownThreshold": 50,
	   "FanSpeed": 12.5
	  },
	  {
	   "UpThreshold": 75,
	   "DownThreshold": 60,
	   "FanSpeed": 25.0
	  },
	  {
	   "UpThreshold": 77,
	   "DownThreshold": 65,
	   "FanSpeed": 50.0
	  },
	  {
	   "UpThreshold": 80,
	   "DownThreshold": 67,
	   "FanSpeed": 75.0
	  },
	  {
	   "UpThreshold": 85,
	   "DownThreshold": 70,
	   "FanSpeed": 100.0
	  }
	 ],
	 "FanSpeedPercentageOverrides": []
	}
 ],
 "RegisterWriteConfigurations": [
	{
	 "WriteMode": "Set",
	 "WriteOccasion": "OnWriteFanSpeed",
	 "Register": 160,
	 "Value": 10,
	 "ResetRequired": true,
	 "ResetValue": 10,
	 "ResetWriteMode": "Set",
	 "Description": "UnknownButWorks1"
	},
	{
	 "WriteMode": "Set",
	 "WriteOccasion": "OnWriteFanSpeed",
	 "Register": 166,
	 "Value": 10,
	 "ResetRequired": true,
	 "ResetValue": 10,
	 "ResetWriteMode": "Set",
	 "Description": "UnknownButWorks2"
	}
 ]
}

=== nbfc-linux/nbfc-linux/AppDirPPDIR/share/nbfc/configs/Acer Aspire 5749.json
{
 "NotebookModel": "Acer Aspire 5749",
 "Author": "Phneom",
 "EcPollInterval": 150,
 "ReadWriteWords": false,
 "CriticalTemperature": 80,
 "FanConfigurations": [
	{
	 "ReadRegister": 85,
	 "WriteRegister": 85,
	 "MinSpeedValue": 0,
	 "MaxSpeedValue": 6,
	 "IndependentReadMinMaxValues": false,
	 "MinSpeedValueRead": 0,
	 "MaxSpeedValueRead": 0,
	 "ResetRequired": true,
	 "FanSpeedResetValue": 1,
	 "FanDisplayName": "main",
	 "TemperatureThresholds": [
	  {
	   "UpThreshold": 60,
	   "DownThreshold": 0,
	   "FanSpeed": 0.0
	  },
	  {
	   "UpThreshold": 70,
	   "DownThreshold": 55,
	   "FanSpeed": 16.666666
	  },
	  {
	   "UpThreshold": 75,
	   "DownThreshold": 65,
	   "FanSpeed": 50.0
	  },
	  {
	   "UpThreshold": 80,
	   "DownThreshold": 70,
	   "FanSpeed": 100.0
	  }
	 ],
	 "FanSpeedPercentageOverrides": []
	}
 ],
 "RegisterWriteConfigurations": []
}

=== nbfc-linux/nbfc-linux/AppDirPPDIR/share/nbfc/configs/Asus ROG G752VS.json
{
 "NotebookModel": "G752VS",
 "Author": "Slartibartfast",
 "EcPollInterval": 150,
 "ReadWriteWords": false,
 "CriticalTemperature": 90,
 "FanConfigurations": [
	{
	 "ReadRegister": 151,
	 "WriteRegister": 151,
	 "MinSpeedValue": 0,
	 "MaxSpeedValue": 8,
	 "IndependentReadMinMaxValues": false,
	 "MinSpeedValueRead": 0,
	 "MaxSpeedValueRead": 0,
	 "ResetRequired": true,
	 "FanSpeedResetValue": 8,
	 "FanDisplayName": "CPU FAN",
	 "TemperatureThresholds": [
	  {
	   "UpThreshold": 65,
	   "DownThreshold": 0,
	   "FanSpeed": 0.0
	  },
	  {
	   "UpThreshold": 70,
	   "DownThreshold": 55,
	   "FanSpeed": 25.0
	  },
	  {
	   "UpThreshold": 80,
	   "DownThreshold": 60,
	   "FanSpeed": 50.0
	  },
	  {
	   "UpThreshold": 85,
	   "DownThreshold": 65,
	   "FanSpeed": 75.0
	  },
	  {
	   "UpThreshold": 90,
	   "DownThreshold": 75,
	   "FanSpeed": 100.0
	  }
	 ],
	 "FanSpeedPercentageOverrides": []
	},
	{
	 "ReadRegister": 152,
	 "WriteRegister": 152,
	 "MinSpeedValue": 0,
	 "MaxSpeedValue": 8,
	 "IndependentReadMinMaxValues": false,
	 "MinSpeedValueRead": 0,
	 "MaxSpeedValueRead": 0,
	 "ResetRequired": true,
	 "FanSpeedResetValue": 8,
	 "FanDisplayName": "GPU FAN",
	 "TemperatureThresholds": [
	  {
	   "UpThreshold": 65,
	   "DownThreshold": 0,
	   "FanSpeed": 0.0
	  },
	  {
	   "UpThreshold": 70,
	   "DownThreshold": 55,
	   "FanSpeed": 25.0
	  },
	  {
	   "UpThreshold": 80,
	   "DownThreshold": 60,
	   "FanSpeed": 50.0
	  },
	  {
	   "UpThreshold": 85,
	   "DownThreshold": 65,
	   "FanSpeed": 75.0
	  },
	  {
	   "UpThreshold": 90,
	   "DownThreshold": 75,
	   "FanSpeed": 100.0
	  }
	 ],
	 "FanSpeedPercentageOverrides": []
	}
 ],
 "RegisterWriteConfigurations": [
	{
	 "WriteMode": "Set",
	 "WriteOccasion": "OnWriteFanSpeed",
	 "Register": 160,
	 "Value": 10,
	 "ResetRequired": true,
	 "ResetValue": 10,
	 "ResetWriteMode": "Set",
	 "Description": "CPU FAN"
	},
	{
	 "WriteMode": "Set",
	 "WriteOccasion": "OnWriteFanSpeed",
	 "Register": 166,
	 "Value": 10,
	 "ResetRequired": true,
	 "ResetValue": 10,
	 "ResetWriteMode": "Set",
	 "Description": "GPU FAN"
	}
 ]
}

=== nbfc-linux/nbfc-linux/AppDirPPDIR/share/nbfc/configs/Sony Corporation VGN-CR392_W.json
{
 "NotebookModel": "Sony Corporation VGN-CR392_W",
 "Author": "Kevin-KD",
 "EcPollInterval": 100,
 "ReadWriteWords": false,
 "CriticalTemperature": 75,
 "FanConfigurations": [
	{
	 "ReadRegister": 91,
	 "WriteRegister": 91,
	 "MinSpeedValue": 142,
	 "MaxSpeedValue": 210,
	 "IndependentReadMinMaxValues": false,
	 "MinSpeedValueRead": 0,
	 "MaxSpeedValueRead": 0,
	 "ResetRequired": false,
	 "FanSpeedResetValue": 0,
	 "FanDisplayName": "Fan",
	 "TemperatureThresholds": [
	  {
	   "UpThreshold": 60,
	   "DownThreshold": 0,
	   "FanSpeed": 0.0
	  },
	  {
	   "UpThreshold": 63,
	   "DownThreshold": 48,
	   "FanSpeed": 10.0
	  },
	  {
	   "UpThreshold": 66,
	   "DownThreshold": 55,
	   "FanSpeed": 20.0
	  },
	  {
	   "UpThreshold": 68,
	   "DownThreshold": 59,
	   "FanSpeed": 50.0
	  },
	  {
	   "UpThreshold": 71,
	   "DownThreshold": 63,
	   "FanSpeed": 70.0
	  },
	  {
	   "UpThreshold": 75,
	   "DownThreshold": 67,
	   "FanSpeed": 100.0
	  }
	 ],
	 "FanSpeedPercentageOverrides": [
	  {
	   "FanSpeedPercentage": 0.0,
	   "FanSpeedValue": 0,
	   "TargetOperation": "ReadWrite"
	  }
	 ]
	},
	{
	 "ReadRegister": 92,
	 "WriteRegister": 92,
	 "MinSpeedValue": 142,
	 "MaxSpeedValue": 210,
	 "IndependentReadMinMaxValues": false,
	 "MinSpeedValueRead": 0,
	 "MaxSpeedValueRead": 0,
	 "ResetRequired": false,
	 "FanSpeedResetValue": 0,
	 "FanDisplayName": "Fan",
	 "TemperatureThresholds": [
	  {
	   "UpThreshold": 60,
	   "DownThreshold": 0,
	   "FanSpeed": 0.0
	  },
	  {
	   "UpThreshold": 63,
	   "DownThreshold": 48,
	   "FanSpeed": 10.0
	  },
	  {
	   "UpThreshold": 66,
	   "DownThreshold": 55,
	   "FanSpeed": 20.0
	  },
	  {
	   "UpThreshold": 68,
	   "DownThreshold": 59,
	   "FanSpeed": 50.0
	  },
	  {
	   "UpThreshold": 71,
	   "DownThreshold": 63,
	   "FanSpeed": 70.0
	  },
	  {
	   "UpThreshold": 75,
	   "DownThreshold": 67,
	   "FanSpeed": 100.0
	  }
	 ],
	 "FanSpeedPercentageOverrides": [
	  {
	   "FanSpeedPercentage": 0.0,
	   "FanSpeedValue": 0,
	   "TargetOperation": "ReadWrite"
	  }
	 ]
	},
	{
	 "ReadRegister": 93,
	 "WriteRegister": 93,
	 "MinSpeedValue": 142,
	 "MaxSpeedValue": 210,
	 "IndependentReadMinMaxValues": false,
	 "MinSpeedValueRead": 0,
	 "MaxSpeedValueRead": 0,
	 "ResetRequired": false,
	 "FanSpeedResetValue": 0,
	 "FanDisplayName": "Fan",
	 "TemperatureThresholds": [
	  {
	   "UpThreshold": 60,
	   "DownThreshold": 0,
	   "FanSpeed": 0.0
	  },
	  {
	   "UpThreshold": 63,
	   "DownThreshold": 48,
	   "FanSpeed": 10.0
	  },
	  {
	   "UpThreshold": 66,
	   "DownThreshold": 55,
	   "FanSpeed": 20.0
	  },
	  {
	   "UpThreshold": 68,
	   "DownThreshold": 59,
	   "FanSpeed": 50.0
	  },
	  {
	   "UpThreshold": 71,
	   "DownThreshold": 63,
	   "FanSpeed": 70.0
	  },
	  {
	   "UpThreshold": 75,
	   "DownThreshold": 67,
	   "FanSpeed": 100.0
	  }
	 ],
	 "FanSpeedPercentageOverrides": [
	  {
	   "FanSpeedPercentage": 0.0,
	   "FanSpeedValue": 0,
	   "TargetOperation": "ReadWrite"
	  }
	 ]
	}
 ],
 "RegisterWriteConfigurations": [
	{
	 "WriteMode": "Set",
	 "WriteOccasion": "OnWriteFanSpeed",
	 "Register": 65,
	 "Value": 19,
	 "ResetRequired": false,
	 "ResetValue": 0,
	 "ResetWriteMode": "Set",
	 "Description": "Switch on fan"
	}
 ]
}

=== nbfc-linux/nbfc-linux/AppDirPPDIR/share/nbfc/configs/Acer Swift SF314-54G.json
{
 "NotebookModel": "Acer Swift SF314-54G",
 "Author": "Cel",
 "EcPollInterval": 4000,
 "ReadWriteWords": false,
 "CriticalTemperature": 95,
 "FanConfigurations": [
	{
	 "ReadRegister": 149,
	 "WriteRegister": 148,
	 "MinSpeedValue": 255,
	 "MaxSpeedValue": 0,
	 "IndependentReadMinMaxValues": false,
	 "MinSpeedValueRead": 0,
	 "MaxSpeedValueRead": 0,
	 "ResetRequired": true,
	 "FanSpeedResetValue": 4,
	 "FanDisplayName": "Main Fan",
	 "TemperatureThresholds": [
	  {
	   "UpThreshold": 55,
	   "DownThreshold": 0,
	   "FanSpeed": 0.0
	  },
	  {
	   "UpThreshold": 62,
	   "DownThreshold": 45,
	   "FanSpeed": 20.0
	  },
	  {
	   "UpThreshold": 68,
	   "DownThreshold": 52,
	   "FanSpeed": 40.0
	  },
	  {
	   "UpThreshold": 74,
	   "DownThreshold": 55,
	   "FanSpeed": 45.4901962
	  },
	  {
	   "UpThreshold": 80,
	   "DownThreshold": 64,
	   "FanSpeed": 50.9803963
	  },
	  {
	   "UpThreshold": 90,
	   "DownThreshold": 65,
	   "FanSpeed": 60.0000038
	  },
	  {
	   "UpThreshold": 94,
	   "DownThreshold": 75,
	   "FanSpeed": 65.4902
	  },
	  {
	   "UpThreshold": 95,
	   "DownThreshold": 65,
	   "FanSpeed": 100.0
	  }
	 ],
	 "FanSpeedPercentageOverrides": []
	}
 ],
 "RegisterWriteConfigurations": [
	{
	 "WriteMode": "Set",
	 "WriteOccasion": "OnInitialization",
	 "Register": 147,
	 "Value": 20,
	 "ResetRequired": true,
	 "ResetValue": 4,
	 "ResetWriteMode": "Set",
	 "Description": "Set Ec"
	}
 ]
}

=== nbfc-linux/nbfc-linux/AppDirPPDIR/share/nbfc/configs/Acer Aspire 5745G.json
{
 "NotebookModel": "Acer Aspire 5745G",
 "Author": "xen20",
 "EcPollInterval": 1000,
 "ReadWriteWords": false,
 "CriticalTemperature": 93,
 "FanConfigurations": [
	{
	 "ReadRegister": 94,
	 "WriteRegister": 94,
	 "MinSpeedValue": 1,
	 "MaxSpeedValue": 13,
	 "IndependentReadMinMaxValues": false,
	 "MinSpeedValueRead": 0,
	 "MaxSpeedValueRead": 0,
	 "ResetRequired": true,
	 "FanSpeedResetValue": 4,
	 "FanDisplayName": "Main",
	 "TemperatureThresholds": [
	  {
	   "UpThreshold": 50,
	   "DownThreshold": 0,
	   "FanSpeed": 0.0
	  },
	  {
	   "UpThreshold": 60,
	   "DownThreshold": 1,
	   "FanSpeed": 0.0
	  },
	  {
	   "UpThreshold": 68,
	   "DownThreshold": 48,
	   "FanSpeed": 16.6666679
	  },
	  {
	   "UpThreshold": 75,
	   "DownThreshold": 58,
	   "FanSpeed": 33.3333359
	  },
	  {
	   "UpThreshold": 82,
	   "DownThreshold": 66,
	   "FanSpeed": 50.0
	  },
	  {
	   "UpThreshold": 93,
	   "DownThreshold": 73,
	   "FanSpeed": 100.0
	  }
	 ],
	 "FanSpeedPercentageOverrides": []
	}
 ],
 "RegisterWriteConfigurations": []
}

=== nbfc-linux/nbfc-linux/AppDirPPDIR/share/nbfc/configs/Acer Aspire VN7-572G V15 Nitro.json
{
 "NotebookModel": "Acer Aspire VN7-572G",
 "Author": "Ivo Pischner",
 "EcPollInterval": 3000,
 "ReadWriteWords": false,
 "CriticalTemperature": 80,
 "FanConfigurations": [
	{
	 "ReadRegister": 149,
	 "WriteRegister": 148,
	 "MinSpeedValue": 255,
	 "MaxSpeedValue": 98,
	 "IndependentReadMinMaxValues": false,
	 "MinSpeedValueRead": 0,
	 "MaxSpeedValueRead": 0,
	 "ResetRequired": true,
	 "FanSpeedResetValue": 255,
	 "FanDisplayName": "Fan",
	 "TemperatureThresholds": [
	  {
	   "UpThreshold": 66,
	   "DownThreshold": 0,
	   "FanSpeed": 0.0
	  },
	  {
	   "UpThreshold": 68,
	   "DownThreshold": 59,
	   "FanSpeed": 10.191083
	  },
	  {
	   "UpThreshold": 71,
	   "DownThreshold": 63,
	   "FanSpeed": 32.4840775
	  },
	  {
	   "UpThreshold": 80,
	   "DownThreshold": 67,
	   "FanSpeed": 100.0
	  }
	 ],
	 "FanSpeedPercentageOverrides": []
	}
 ],
 "RegisterWriteConfigurations": [
	{
	 "WriteMode": "Set",
	 "WriteOccasion": "OnInitialization",
	 "Register": 147,
	 "Value": 20,
	 "ResetRequired": true,
	 "ResetValue": 4,
	 "ResetWriteMode": "Set",
	 "Description": "Set EC to manual control"
	}
 ]
}
