=== nbfc-linux/nbfc-linux/tools/FanControlConfigV3-v1.0.0-schema.json
{
  "$schema": "https://json-schema.org/draft-07/schema",
  "$description": "Schema for nbfc-linux for controlling fans of notebooks",
  "type": "object",
  "properties": {
    "SelectedConfigId": {
      "type": "string",
      "description": "The selected config model. This equals the basename of a notebook model configuration file.",
      "default": ""
    },
    "LegacyTemperatureThresholdsBehaviour": {
      "type": "boolean",
      "description": "Backwards compatibilty with configuration files from the original NBFC project. The default is false. Do not use this option for new configuration files.",
      "default": false,
      "enum": [true, false]
    },
    "EmbeddedControllerType": {
      "type": "string",
      "description": "The preferred way of running nbfc. If not given, the embedded controller type will be automatically selected.",
      "default": "",
      "anyOf": [
        {
          "const": "ec_sys",
          "description": "Use the ec_sys kernel module for writing to the embedded controller."
        },
        {
          "const": "acpi_ec",
          "description": "Use the acpi_ec kernel module for writing to the embedded controller."
        },
        {
          "const": "dev_port",
          "description": "Write to the embedded controller using /dev/port."
        },
        {
          "const": "dummy",
          "description": "Don't write to the embedded controller at all."
        },
        {
          "const": "",
          "description": "The embedded controller type will be automatically selected."
        }
      ]
    },
    "NotebookModel": {
      "type": "string",
      "description": "The Notebook Model as described in your BIOS. See `sudo dmidecode -s system-product-name`."
    },
    "Author": {
      "type": "string",
      "description": "The Author of the config file. Enter whatever you want.",
      "default": ""
    },
    "EcPollInterval": {
      "type": "integer",
      "description": "Defines how often NBFC polls the EC for changes (in miliseconds).",
      "default": "3000",
      "minimum": 1,
      "maximum": 32768
    },
    "ReadWriteWords": {
      "type": "boolean",
      "description": "If `true`, NBFC will combine two 8 bit registers to one 16-bit register when reading from or writing to the EC registers.",
      "default": false,
      "enum": [true, false]
    },
    "CriticalTemperature": {
      "type": "integer",
      "description": "If the temperature exceeds this threshold, NBFC will ignore all Temperature threshold elements and set the fan to 100% speed until the temperature drops below (`CriticalTemperature` - `CriticalTemperatureOffset`)",
      "default": 75,
      "minimum": 0,
      "maximum": 100
    },
    "CriticalTemperatureOffset": {
      "type": "integer",
      "description": "See `CriticalTemperature`",
      "default": 15,
      "minimum": 32768
    },
    "TargetFanSpeeds": {
      "type": "array",
      "description": "This holds the fixed speed of the fans. A value of -1 means the fan should be left in auto mode.",
      "minProperties": 0,
      "items": [
        {
          "type": "integer",
          "minimum": -1,
          "maximum": 65535
        }
      ]
    },
    "FanConfigurations": {
      "type": "array",
      "description": "Array of at least one FanConfiguration",
      "minProperties": 1,
      "items": {
        "type": "object",
        "title": "FanConfiguration",
        "description": "Defines how NBFC controls a fan",
        "properties": {
          "ReadRegister": {
            "$ref": "#/$defs/ubyte",
            "description": "The register from which NBFC reads the fan speed."
          },
          "WriteRegister": {
            "$ref": "#/$defs/ubyte",
            "description": "The register which NBFC uses to control the fan"
          },
          "MinSpeedValue": {
            "$ref": "#/$defs/uword",
            "description": "The value which puts the fan to the lowest possible speed (usually this stops the fan). Must be an integer between 0 and 255 or 0 and 65535 if ReadWriteWords is `true`. Note: MinSpeedValue does not necessarily have to be smaller than MaxSpeedValue"
          },
          "MaxSpeedValue": {
            "$ref": "#/$defs/uword",
            "description": "The value which puts the fan to the highest possible fan speed."
          },
          "IndependentReadMinMaxValues": {
            "type": "boolean",
            "default": false,
            "enum": [true, false],
            "description": "Defines if independent minimum/maximum values should be applied for read operations"
          },
          "MinSpeedValueRead": {
            "$ref": "#/$defs/uword",
            "description": "The value which corresponds to the lowest possible fan speed. Will be ignored if IndependentReadMinMaxValues is `false`."
          },
          "MaxSpeedValueRead": {
            "$ref": "#/$defs/uword",
            "description": "The value which  corresponds to the highest possible fan speed. Will be ignored if IndependentReadMinMaxValues is `false`."
          },
          "ResetRequired": {
            "type": "boolean",
            "default": false,
            "enum": [true, false],
            "description": "Defines if the EC should be reset before the service is shut down."
          },
          "FanSpeedResetValue": {
            "$ref": "#/$defs/uword",
            "description": "Defines the value which will be written to WriteRegister to reset the EC."
          },
          "FanDisplayName": {
            "type": "string",
            "description": "Fan display name",
            "default": ""
          },
          "SleepOverrideRequired": {
            "type": "boolean",
            "default": false,
            "enum": [true, false],
            "description": "Defines if the fan speed value should be overridden while the system is going to sleep until it is resumed."
          },
          "SleepFanSpeedOverrideValue": {
            "$ref": "#/$defs/uword",
            "description": "Defines the value which will be written to WriteRegister before the system is going to sleep."
          },
          "TemperatureThresholds": {
            "type": "array",
            "description": "Defines how fast the fan runs at different temperatures",
            "items": {
              "type": "object",
              "properties": {
                "UpThreshold": {
                  "$ref": "#/$defs/ubyte",
                  "description": "NBFC will select the next upper threshold as soon as the temperature exceeds *UpThreshold*. in celsius"
                },
                "DownThreshold": {
                  "$ref": "#/$defs/ubyte",
                  "description": "NBFC will select the next lower threshold as soon as the temperature falls below the *DownThreshold*. in celsius"
                },
                "FanSpeed": {
                  "$ref": "#/$defs/percentage",
                  "description": "The fan speed in percent"
                }
              },
              "required": ["UpThreshold", "DownThreshold", "FanSpeed"]
            }
          },
          "FanSpeedPercentageOverrides": {
            "type": "array",
            "description": "Overrides the default algorithm to calculate fan speeds",
            "items": {
              "type": "object",
              "properties": {
                "FanSpeedPercentage": {
                  "$ref": "#/$defs/percentage",
                  "description": "The fan speed in percent"
                },
                "FanSpeedValue": {
                  "$ref": "#/$defs/uword",
                  "description": "Fan speed value which will be written to WriteRegister"
                },
                "TargetOperation": {
                  "type": "string",
                  "default": "ReadWrite",
                  "anyOf": [
                    {
                      "const": "Read",
                      "description": "Value->Percentage"
                    },
                    {
                      "const": "Write",
                      "description": "Percentage->Value"
                    },
                    {
                      "const": "ReadWrite",
                      "description": "both"
                    }
                  ],
                  "description": "Defines for which operations the speeds should be overridden."
                }
              }
            }
          }
        },
        "required": [
          "ReadRegister",
          "WriteRegister",
          "MinSpeedValue",
          "MaxSpeedValue",
          "IndependentReadMinMaxValues",
          "MinSpeedValueRead",
          "MaxSpeedValueRead",
          "ResetRequired",
          "FanSpeedResetValue",
          "FanDisplayName",
          "TemperatureThresholds",
          "FanSpeedPercentageOverrides"
        ]
      }
    },
    "RegisterWriteConfigurations": {
      "type": "array",
      "description": "Allows to write to any EC register",
      "items": {
        "type": "object",
        "properties": {
          "WriteMode": {
            "$ref": "#/$defs/writeModeDef",
            "description": "Defines how the value will be written"
          },
          "WriteOccasion": {
            "type": "string",
            "description": "Defines when the value should be written",
            "default": "OnInitialization",
            "anyOf": [
              {
                "const": "OnInitialization",
                "description": "writes the value once upon initialization (everytime the fan control service is enabled or a config is applied)"
              },
              {
                "const": "OnWriteFanSpeed",
                "description": "writes the value everytime the fan speed is set."
              }
            ]
          },
          "Register": {
            "$ref": "#/$defs/ubyte",
            "description": "The register which will be manipulated."
          },
          "Value": {
            "$ref": "#/$defs/uword",
            "description": "The Value which will be written"
          },
          "ResetRequired": {
            "type": "boolean",
            "description": "Defines if the register should be reset before the service is shut down.",
            "enum": [true, false],
            "default": false
          },
          "ResetValue": {
            "$ref": "#/$defs/uword",
            "description": "The value which will be written upon reset."
          },
          "ResetWriteMode": {
            "$ref": "#/$defs/writeModeDef",
            "description": "See WriteMode. Will only be applied on reset"
          },
          "Description": {
            "type": "string",
            "description": "A description of what effect the RegisterWriteConfiguration will have",
            "default": ""
          }
        },
        "required": [
          "WriteMode",
          "WriteOccasion",
          "Register",
          "Value",
          "ResetRequired",
          "ResetValue",
          "ResetWriteMode",
          "Description"
        ]
      }
    }
  },
  "required": [
    "NotebookModel",
    "Author",
    "EcPollInterval",
    "ReadWriteWords",
    "CriticalTemperature",
    "FanConfigurations",
    "RegisterWriteConfigurations"
  ],
  "$defs": {
    "writeModeDef": {
      "type": "string",
      "default": "Set",
      "anyOf": [
        {
          "const": "And",
          "description": "register = register bitwise_and value"
        },
        {
          "const": "Or",
          "description": "register = register bitwise_or value"
        },
        {
          "const": "Set",
          "description": "register = value"
        }
      ]
    },
    "ubyte": {
      "type": "integer",
      "minimum": 0,
      "maximum": 255
    },
    "percentage": {
      "type": "number",
      "minimum": 0.0,
      "maximum": 100.0
    },
    "uword": {
      "type": "integer",
      "minimum": 0,
      "maximum": 65535
    }
  }
}

=== nbfc-linux/nbfc-linux/AppDirPPDIR/share/nbfc/configs/MECHREVO Jiaolong Series GK5NR0O.json
{
 "NotebookModel": "MECHREVO Jiaolong Series GK5NR0O",
 "Author": "None",
 "EcPollInterval": 3000,
 "ReadWriteWords": false,
 "CriticalTemperature": 88,
 "FanConfigurations": [
	{
	 "ReadRegister": 62,
	 "WriteRegister": 62,
	 "MinSpeedValue": 31,
	 "MaxSpeedValue": 78,
	 "IndependentReadMinMaxValues": false,
	 "MinSpeedValueRead": 0,
	 "MaxSpeedValueRead": 0,
	 "ResetRequired": false,
	 "FanSpeedResetValue": 0,
	 "FanDisplayName": "Fan",
	 "TemperatureThresholds": [
	  {
	   "UpThreshold": 45,
	   "DownThreshold": 0,
	   "FanSpeed": 0.0
	  },
	  {
	   "UpThreshold": 50,
	   "DownThreshold": 41,
	   "FanSpeed": 6.5
	  },
	  {
	   "UpThreshold": 60,
	   "DownThreshold": 46,
	   "FanSpeed": 10.0
	  },
	  {
	   "UpThreshold": 65,
	   "DownThreshold": 51,
	   "FanSpeed": 30.0
	  },
	  {
	   "UpThreshold": 87,
	   "DownThreshold": 61,
	   "FanSpeed": 50.0
	  },
	  {
	   "UpThreshold": 88,
	   "DownThreshold": 66,
	   "FanSpeed": 100.0
	  }
	 ],
	 "FanSpeedPercentageOverrides": []
	}
 ],
 "RegisterWriteConfigurations": []
}

=== nbfc-linux/nbfc-linux/AppDirPPDIR/share/nbfc/configs/HP Laptop 17-ca1xxx.json
{
 "NotebookModel": "HP Laptop 17-ca1xxx",
 "Author": "Harald Rohan",
 "EcPollInterval": 200,
 "ReadWriteWords": false,
 "CriticalTemperature": 81,
 "FanConfigurations": [
	{
	 "ReadRegister": 128,
	 "WriteRegister": 219,
	 "MinSpeedValue": 34,
	 "MaxSpeedValue": 80,
	 "IndependentReadMinMaxValues": true,
	 "MinSpeedValueRead": 0,
	 "MaxSpeedValueRead": 7,
	 "ResetRequired": false,
	 "FanSpeedResetValue": 255,
	 "FanDisplayName": "CPU fan",
	 "TemperatureThresholds": [
	  {
	   "UpThreshold": 60,
	   "DownThreshold": 0,
	   "FanSpeed": 0.0
	  },
	  {
	   "UpThreshold": 65,
	   "DownThreshold": 50,
	   "FanSpeed": 20.0
	  },
	  {
	   "UpThreshold": 70,
	   "DownThreshold": 55,
	   "FanSpeed": 40.0
	  },
	  {
	   "UpThreshold": 75,
	   "DownThreshold": 60,
	   "FanSpeed": 60.0
	  },
	  {
	   "UpThreshold": 80,
	   "DownThreshold": 65,
	   "FanSpeed": 80.0
	  },
	  {
	   "UpThreshold": 81,
	   "DownThreshold": 70,
	   "FanSpeed": 100.0
	  }
	 ],
	 "FanSpeedPercentageOverrides": []
	}
 ],
 "RegisterWriteConfigurations": []
}

=== nbfc-linux/nbfc-linux/AppDirPPDIR/share/nbfc/configs/HP ZBook 15 G3.json
{
 "NotebookModel": "HP ZBook 15 G3",
 "Author": "Tijmen van Nisselrooij",
 "EcPollInterval": 1000,
 "ReadWriteWords": false,
 "CriticalTemperature": 85,
 "FanConfigurations": [
	{
	 "ReadRegister": 46,
	 "WriteRegister": 47,
	 "MinSpeedValue": 164,
	 "MaxSpeedValue": 60,
	 "IndependentReadMinMaxValues": false,
	 "MinSpeedValueRead": 0,
	 "MaxSpeedValueRead": 0,
	 "ResetRequired": true,
	 "FanSpeedResetValue": 255,
	 "FanDisplayName": "Left CPU fan",
	 "TemperatureThresholds": [
	  {
	   "UpThreshold": 60,
	   "DownThreshold": 0,
	   "FanSpeed": 0.0
	  },
	  {
	   "UpThreshold": 67,
	   "DownThreshold": 56,
	   "FanSpeed": 20.0
	  },
	  {
	   "UpThreshold": 75,
	   "DownThreshold": 63,
	   "FanSpeed": 30.0
	  },
	  {
	   "UpThreshold": 80,
	   "DownThreshold": 71,
	   "FanSpeed": 60.0
	  },
	  {
	   "UpThreshold": 85,
	   "DownThreshold": 76,
	   "FanSpeed": 100.0
	  }
	 ],
	 "FanSpeedPercentageOverrides": [
	  {
	   "FanSpeedPercentage": 0.0,
	   "FanSpeedValue": 255,
	   "TargetOperation": "ReadWrite"
	  }
	 ]
	},
	{
	 "ReadRegister": 53,
	 "WriteRegister": 54,
	 "MinSpeedValue": 164,
	 "MaxSpeedValue": 60,
	 "IndependentReadMinMaxValues": false,
	 "MinSpeedValueRead": 0,
	 "MaxSpeedValueRead": 0,
	 "ResetRequired": true,
	 "FanSpeedResetValue": 255,
	 "FanDisplayName": "Right CPU Fan",
	 "TemperatureThresholds": [
	  {
	   "UpThreshold": 60,
	   "DownThreshold": 0,
	   "FanSpeed": 0.0
	  },
	  {
	   "UpThreshold": 67,
	   "DownThreshold": 56,
	   "FanSpeed": 20.0
	  },
	  {
	   "UpThreshold": 75,
	   "DownThreshold": 63,
	   "FanSpeed": 30.0
	  },
	  {
	   "UpThreshold": 80,
	   "DownThreshold": 71,
	   "FanSpeed": 60.0
	  },
	  {
	   "UpThreshold": 85,
	   "DownThreshold": 76,
	   "FanSpeed": 100.0
	  }
	 ],
	 "FanSpeedPercentageOverrides": [
	  {
	   "FanSpeedPercentage": 0.0,
	   "FanSpeedValue": 255,
	   "TargetOperation": "ReadWrite"
	  }
	 ]
	}
 ],
 "RegisterWriteConfigurations": [
	{
	 "WriteMode": "Set",
	 "WriteOccasion": "OnInitialization",
	 "Register": 34,
	 "Value": 1,
	 "ResetRequired": true,
	 "ResetValue": 1,
	 "ResetWriteMode": "Set",
	 "Description": "Select thermal zone"
	},
	{
	 "WriteMode": "Set",
	 "WriteOccasion": "OnInitialization",
	 "Register": 38,
	 "Value": 28,
	 "ResetRequired": true,
	 "ResetValue": 0,
	 "ResetWriteMode": "Set",
	 "Description": "Fake thermal zone temperature"
	}
 ]
}

=== nbfc-linux/nbfc-linux/share/nbfc/configs/HP ProBook 650 G2.json
{
 "LegacyTemperatureThresholdsBehaviour": true,
 "NotebookModel": "HP ProBook 650 G2",
 "Author": "Christian Malek",
 "EcPollInterval": 3000,
 "ReadWriteWords": false,
 "CriticalTemperature": 75,
 "FanConfigurations": [
	{
	 "ReadRegister": 46,
	 "WriteRegister": 47,
	 "MinSpeedValue": 123,
	 "MaxSpeedValue": 48,
	 "IndependentReadMinMaxValues": false,
	 "MinSpeedValueRead": 0,
	 "MaxSpeedValueRead": 0,
	 "ResetRequired": true,
	 "FanSpeedResetValue": 255,
	 "FanDisplayName": "CPU fan",
	 "TemperatureThresholds": [
	  {
	   "UpThreshold": 0,
	   "DownThreshold": 0,
	   "FanSpeed": 20.0
	  },
	  {
	   "UpThreshold": 66,
	   "DownThreshold": 59,
	   "FanSpeed": 50.0
	  },
	  {
	   "UpThreshold": 71,
	   "DownThreshold": 65,
	   "FanSpeed": 100.0
	  }
	 ],
	 "FanSpeedPercentageOverrides": [
	  {
	   "FanSpeedPercentage": 0.0,
	   "FanSpeedValue": 254,
	   "TargetOperation": "ReadWrite"
	  },
	  {
	   "FanSpeedPercentage": 0.0,
	   "FanSpeedValue": 255,
	   "TargetOperation": "Read"
	  }
	 ]
	}
 ],
 "RegisterWriteConfigurations": [
	{
	 "WriteMode": "Set",
	 "WriteOccasion": "OnInitialization",
	 "Register": 34,
	 "Value": 1,
	 "ResetRequired": true,
	 "ResetValue": 1,
	 "ResetWriteMode": "Set",
	 "Description": "Select thermal zone"
	},
	{
	 "WriteMode": "Set",
	 "WriteOccasion": "OnInitialization",
	 "Register": 38,
	 "Value": 28,
	 "ResetRequired": true,
	 "ResetValue": 0,
	 "ResetWriteMode": "Set",
	 "Description": "Fake thermal zone temperature"
	}
 ]
}

=== nbfc-linux/nbfc-linux/share/nbfc/configs/HP ZBook Studio G3.json
{
 "LegacyTemperatureThresholdsBehaviour": true,
 "NotebookModel": "HP ZBook Studio G3",
 "Author": "Mahmoud Al-Qudsi",
 "EcPollInterval": 1000,
 "ReadWriteWords": false,
 "CriticalTemperature": 85,
 "FanConfigurations": [
	{
	 "ReadRegister": 46,
	 "WriteRegister": 47,
	 "MinSpeedValue": 88,
	 "MaxSpeedValue": 46,
	 "IndependentReadMinMaxValues": false,
	 "MinSpeedValueRead": 0,
	 "MaxSpeedValueRead": 0,
	 "ResetRequired": true,
	 "FanSpeedResetValue": 255,
	 "FanDisplayName": "CPU fan",
	 "TemperatureThresholds": [
	  {
	   "UpThreshold": 0,
	   "DownThreshold": 0,
	   "FanSpeed": 0.0
	  },
	  {
	   "UpThreshold": 70,
	   "DownThreshold": 65,
	   "FanSpeed": 20.0
	  },
	  {
	   "UpThreshold": 74,
	   "DownThreshold": 70,
	   "FanSpeed": 30.0
	  },
	  {
	   "UpThreshold": 77,
	   "DownThreshold": 74,
	   "FanSpeed": 60.0
	  },
	  {
	   "UpThreshold": 80,
	   "DownThreshold": 76,
	   "FanSpeed": 100.0
	  }
	 ],
	 "FanSpeedPercentageOverrides": [
	  {
	   "FanSpeedPercentage": 0.0,
	   "FanSpeedValue": 255,
	   "TargetOperation": "ReadWrite"
	  }
	 ]
	},
	{
	 "ReadRegister": 53,
	 "WriteRegister": 54,
	 "MinSpeedValue": 88,
	 "MaxSpeedValue": 46,
	 "IndependentReadMinMaxValues": false,
	 "MinSpeedValueRead": 0,
	 "MaxSpeedValueRead": 0,
	 "ResetRequired": true,
	 "FanSpeedResetValue": 255,
	 "FanDisplayName": "CPU Fan 2",
	 "TemperatureThresholds": [
	  {
	   "UpThreshold": 0,
	   "DownThreshold": 0,
	   "FanSpeed": 0.0
	  },
	  {
	   "UpThreshold": 70,
	   "DownThreshold": 65,
	   "FanSpeed": 20.0
	  },
	  {
	   "UpThreshold": 74,
	   "DownThreshold": 70,
	   "FanSpeed": 30.0
	  },
	  {
	   "UpThreshold": 77,
	   "DownThreshold": 74,
	   "FanSpeed": 60.0
	  },
	  {
	   "UpThreshold": 80,
	   "DownThreshold": 76,
	   "FanSpeed": 100.0
	  }
	 ],
	 "FanSpeedPercentageOverrides": [
	  {
	   "FanSpeedPercentage": 0.0,
	   "FanSpeedValue": 255,
	   "TargetOperation": "ReadWrite"
	  }
	 ]
	}
 ],
 "RegisterWriteConfigurations": [
	{
	 "WriteMode": "Set",
	 "WriteOccasion": "OnInitialization",
	 "Register": 34,
	 "Value": 1,
	 "ResetRequired": true,
	 "ResetValue": 1,
	 "ResetWriteMode": "Set",
	 "Description": "Select thermal zone"
	},
	{
	 "WriteMode": "Set",
	 "WriteOccasion": "OnInitialization",
	 "Register": 38,
	 "Value": 28,
	 "ResetRequired": true,
	 "ResetValue": 0,
	 "ResetWriteMode": "Set",
	 "Description": "Fake thermal zone temperature"
	}
 ]
}

=== nbfc-linux/nbfc-linux/share/nbfc/configs/HP Pavilion x360 Convertible 14-dh1xxx.json
{
 "LegacyTemperatureThresholdsBehaviour": true,
 "NotebookModel": "HP Pavilion x360 Convertible 14-dh1xxx",
 "Author": "Jakov Gudec",
 "EcPollInterval": 200,
 "ReadWriteWords": true,
 "CriticalTemperature": 92,
 "FanConfigurations": [
	{
	 "ReadRegister": 149,
	 "WriteRegister": 148,
	 "MinSpeedValue": 175,
	 "MaxSpeedValue": 75,
	 "IndependentReadMinMaxValues": false,
	 "MinSpeedValueRead": 0,
	 "MaxSpeedValueRead": 0,
	 "ResetRequired": false,
	 "FanSpeedResetValue": 255,
	 "FanDisplayName": "CPU fan",
	 "TemperatureThresholds": [
	  {
	   "UpThreshold": 0,
	   "DownThreshold": 0,
	   "FanSpeed": 0.0
	  },
	  {
	   "UpThreshold": 68,
	   "DownThreshold": 63,
	   "FanSpeed": 20.0
	  },
	  {
	   "UpThreshold": 71,
	   "DownThreshold": 67,
	   "FanSpeed": 35.0
	  },
	  {
	   "UpThreshold": 78,
	   "DownThreshold": 71,
	   "FanSpeed": 50.0
	  },
	  {
	   "UpThreshold": 82,
	   "DownThreshold": 78,
	   "FanSpeed": 65.0
	  },
	  {
	   "UpThreshold": 86,
	   "DownThreshold": 82,
	   "FanSpeed": 85.0
	  },
	  {
	   "UpThreshold": 90,
	   "DownThreshold": 86,
	   "FanSpeed": 100.0
	  }
	 ],
	 "FanSpeedPercentageOverrides": [
	  {
	   "FanSpeedPercentage": 0.0,
	   "FanSpeedValue": 255,
	   "TargetOperation": "ReadWrite"
	  }
	 ]
	}
 ],
 "RegisterWriteConfigurations": [
	{
	 "WriteMode": "Set",
	 "WriteOccasion": "OnInitialization",
	 "Register": 147,
	 "Value": 20,
	 "ResetRequired": true,
	 "ResetValue": 4,
	 "ResetWriteMode": "Set",
	 "Description": "Set EC to manual control"
	}
 ]
}

=== nbfc-linux/nbfc-linux/AppDirPPDIR/share/nbfc/configs/HP Pavilion dv6.json
{
 "NotebookModel": "HP Pavilion dv6 Notebook PC",
 "Author": "unknown, Rany H.",
 "EcPollInterval": 3000,
 "ReadWriteWords": false,
 "CriticalTemperature": 90,
 "FanConfigurations": [
	{
	 "ReadRegister": 177,
	 "WriteRegister": 177,
	 "MinSpeedValue": 9,
	 "MaxSpeedValue": 23,
	 "IndependentReadMinMaxValues": false,
	 "MinSpeedValueRead": 9,
	 "MaxSpeedValueRead": 20,
	 "ResetRequired": true,
	 "FanSpeedResetValue": 0,
	 "FanDisplayName": "None",
	 "TemperatureThresholds": [
	  {
	   "UpThreshold": 45,
	   "DownThreshold": 0,
	   "FanSpeed": 0.0
	  },
	  {
	   "UpThreshold": 57,
	   "DownThreshold": 45,
	   "FanSpeed": 10.0
	  },
	  {
	   "UpThreshold": 70,
	   "DownThreshold": 55,
	   "FanSpeed": 20.0
	  },
	  {
	   "UpThreshold": 85,
	   "DownThreshold": 59,
	   "FanSpeed": 50.0
	  },
	  {
	   "UpThreshold": 88,
	   "DownThreshold": 76,
	   "FanSpeed": 70.0
	  },
	  {
	   "UpThreshold": 90,
	   "DownThreshold": 85,
	   "FanSpeed": 100.0
	  }
	 ],
	 "FanSpeedPercentageOverrides": []
	}
 ],
 "RegisterWriteConfigurations": []
}

=== nbfc-linux/nbfc-linux/AppDirPPDIR/share/nbfc/configs/Asus ROG G75VX.json
{
 "NotebookModel": "Asus ROG G75VX",
 "Author": "RypeDub - https://www.YouTube.com/RypeDub",
 "EcPollInterval": 100,
 "ReadWriteWords": false,
 "CriticalTemperature": 91,
 "FanConfigurations": [
	{
	 "ReadRegister": 151,
	 "WriteRegister": 151,
	 "MinSpeedValue": 0,
	 "MaxSpeedValue": 9,
	 "IndependentReadMinMaxValues": false,
	 "MinSpeedValueRead": 0,
	 "MaxSpeedValueRead": 0,
	 "ResetRequired": false,
	 "FanSpeedResetValue": 0,
	 "FanDisplayName": "Intel Core i7-3630QM CPU Fan",
	 "TemperatureThresholds": [
	  {
	   "UpThreshold": 50,
	   "DownThreshold": 40,
	   "FanSpeed": 0.0
	  },
	  {
	   "UpThreshold": 55,
	   "DownThreshold": 45,
	   "FanSpeed": 11.1111116
	  },
	  {
	   "UpThreshold": 60,
	   "DownThreshold": 50,
	   "FanSpeed": 22.2222233
	  },
	  {
	   "UpThreshold": 65,
	   "DownThreshold": 55,
	   "FanSpeed": 33.3333359
	  },
	  {
	   "UpThreshold": 70,
	   "DownThreshold": 60,
	   "FanSpeed": 44.4444466
	  },
	  {
	   "UpThreshold": 75,
	   "DownThreshold": 65,
	   "FanSpeed": 55.5555573
	  },
	  {
	   "UpThreshold": 80,
	   "DownThreshold": 70,
	   "FanSpeed": 66.66667
	  },
	  {
	   "UpThreshold": 85,
	   "DownThreshold": 75,
	   "FanSpeed": 77.77778
	  },
	  {
	   "UpThreshold": 90,
	   "DownThreshold": 80,
	   "FanSpeed": 88.88889
	  },
	  {
	   "UpThreshold": 91,
	   "DownThreshold": 85,
	   "FanSpeed": 100.0
	  }
	 ],
	 "FanSpeedPercentageOverrides": [
	  {
	   "FanSpeedPercentage": 100.0,
	   "FanSpeedValue": 255,
	   "TargetOperation": "ReadWrite"
	  }
	 ]
	},
	{
	 "ReadRegister": 152,
	 "WriteRegister": 152,
	 "MinSpeedValue": 0,
	 "MaxSpeedValue": 9,
	 "IndependentReadMinMaxValues": false,
	 "MinSpeedValueRead": 0,
	 "MaxSpeedValueRead": 0,
	 "ResetRequired": false,
	 "FanSpeedResetValue": 0,
	 "FanDisplayName": "nVidia GTX 670MX GPU Fan",
	 "TemperatureThresholds": [
	  {
	   "UpThreshold": 50,
	   "DownThreshold": 40,
	   "FanSpeed": 0.0
	  },
	  {
	   "UpThreshold": 55,
	   "DownThreshold": 45,
	   "FanSpeed": 11.1111116
	  },
	  {
	   "UpThreshold": 60,
	   "DownThreshold": 50,
	   "FanSpeed": 22.2222233
	  },
	  {
	   "UpThreshold": 65,
	   "DownThreshold": 55,
	   "FanSpeed": 33.3333359
	  },
	  {
	   "UpThreshold": 70,
	   "DownThreshold": 60,
	   "FanSpeed": 44.4444466
	  },
	  {
	   "UpThreshold": 75,
	   "DownThreshold": 65,
	   "FanSpeed": 55.5555573
	  },
	  {
	   "UpThreshold": 80,
	   "DownThreshold": 70,
	   "FanSpeed": 66.66667
	  },
	  {
	   "UpThreshold": 85,
	   "DownThreshold": 75,
	   "FanSpeed": 77.77778
	  },
	  {
	   "UpThreshold": 90,
	   "DownThreshold": 80,
	   "FanSpeed": 88.88889
	  },
	  {
	   "UpThreshold": 91,
	   "DownThreshold": 85,
	   "FanSpeed": 100.0
	  }
	 ],
	 "FanSpeedPercentageOverrides": [
	  {
	   "FanSpeedPercentage": 100.0,
	   "FanSpeedValue": 255,
	   "TargetOperation": "ReadWrite"
	  }
	 ]
	}
 ],
 "RegisterWriteConfigurations": []
}
