=== nbfc-linux/nbfc-linux/tools/FanControlConfigV3-v1.0.0-schema.json
{
  "$schema": "https://json-schema.org/draft-07/schema",
  "$description": "Schema for nbfc-linux for controlling fans of notebooks",
  "type": "object",
  "properties": {
    "SelectedConfigId": {
      "type": "string",
      "description": "The selected config model. This equals the basename of a notebook model configuration file.",
      "default": ""
    },
    "LegacyTemperatureThresholdsBehaviour": {
      "type": "boolean",
      "description": "Backwards compatibilty with configuration files from the original NBFC project. The default is false. Do not use this option for new configuration files.",
      "default": false,
      "enum": [true, false]
    },
    "EmbeddedControllerType": {
      "type": "string",
      "description": "The preferred way of running nbfc. If not given, the embedded controller type will be automatically selected.",
      "default": "",
      "anyOf": [
        {
          "const": "ec_sys",
          "description": "Use the ec_sys kernel module for writing to the embedded controller."
        },
        {
          "const": "acpi_ec",
          "description": "Use the acpi_ec kernel module for writing to the embedded controller."
        },
        {
          "const": "dev_port",
          "description": "Write to the embedded controller using /dev/port."
        },
        {
          "const": "dummy",
          "description": "Don't write to the embedded controller at all."
        },
        {
          "const": "",
          "description": "The embedded controller type will be automatically selected."
        }
      ]
    },
    "NotebookModel": {
      "type": "string",
      "description": "The Notebook Model as described in your BIOS. See `sudo dmidecode -s system-product-name`."
    },
    "Author": {
      "type": "string",
      "description": "The Author of the config file. Enter whatever you want.",
      "default": ""
    },
    "EcPollInterval": {
      "type": "integer",
      "description": "Defines how often NBFC polls the EC for changes (in miliseconds).",
      "default": "3000",
      "minimum": 1,
      "maximum": 32768
    },
    "ReadWriteWords": {
      "type": "boolean",
      "description": "If `true`, NBFC will combine two 8 bit registers to one 16-bit register when reading from or writing to the EC registers.",
      "default": false,
      "enum": [true, false]
    },
    "CriticalTemperature": {
      "type": "integer",
      "description": "If the temperature exceeds this threshold, NBFC will ignore all Temperature threshold elements and set the fan to 100% speed until the temperature drops below (`CriticalTemperature` - `CriticalTemperatureOffset`)",
      "default": 75,
      "minimum": 0,
      "maximum": 100
    },
    "CriticalTemperatureOffset": {
      "type": "integer",
      "description": "See `CriticalTemperature`",
      "default": 15,
      "minimum": 32768
    },
    "TargetFanSpeeds": {
      "type": "array",
      "description": "This holds the fixed speed of the fans. A value of -1 means the fan should be left in auto mode.",
      "minProperties": 0,
      "items": [
        {
          "type": "integer",
          "minimum": -1,
          "maximum": 65535
        }
      ]
    },
    "FanConfigurations": {
      "type": "array",
      "description": "Array of at least one FanConfiguration",
      "minProperties": 1,
      "items": {
        "type": "object",
        "title": "FanConfiguration",
        "description": "Defines how NBFC controls a fan",
        "properties": {
          "ReadRegister": {
            "$ref": "#/$defs/ubyte",
            "description": "The register from which NBFC reads the fan speed."
          },
          "WriteRegister": {
            "$ref": "#/$defs/ubyte",
            "description": "The register which NBFC uses to control the fan"
          },
          "MinSpeedValue": {
            "$ref": "#/$defs/uword",
            "description": "The value which puts the fan to the lowest possible speed (usually this stops the fan). Must be an integer between 0 and 255 or 0 and 65535 if ReadWriteWords is `true`. Note: MinSpeedValue does not necessarily have to be smaller than MaxSpeedValue"
          },
          "MaxSpeedValue": {
            "$ref": "#/$defs/uword",
            "description": "The value which puts the fan to the highest possible fan speed."
          },
          "IndependentReadMinMaxValues": {
            "type": "boolean",
            "default": false,
            "enum": [true, false],
            "description": "Defines if independent minimum/maximum values should be applied for read operations"
          },
          "MinSpeedValueRead": {
            "$ref": "#/$defs/uword",
            "description": "The value which corresponds to the lowest possible fan speed. Will be ignored if IndependentReadMinMaxValues is `false`."
          },
          "MaxSpeedValueRead": {
            "$ref": "#/$defs/uword",
            "description": "The value which  corresponds to the highest possible fan speed. Will be ignored if IndependentReadMinMaxValues is `false`."
          },
          "ResetRequired": {
            "type": "boolean",
            "default": false,
            "enum": [true, false],
            "description": "Defines if the EC should be reset before the service is shut down."
          },
          "FanSpeedResetValue": {
            "$ref": "#/$defs/uword",
            "description": "Defines the value which will be written to WriteRegister to reset the EC."
          },
          "FanDisplayName": {
            "type": "string",
            "description": "Fan display name",
            "default": ""
          },
          "SleepOverrideRequired": {
            "type": "boolean",
            "default": false,
            "enum": [true, false],
            "description": "Defines if the fan speed value should be overridden while the system is going to sleep until it is resumed."
          },
          "SleepFanSpeedOverrideValue": {
            "$ref": "#/$defs/uword",
            "description": "Defines the value which will be written to WriteRegister before the system is going to sleep."
          },
          "TemperatureThresholds": {
            "type": "array",
            "description": "Defines how fast the fan runs at different temperatures",
            "items": {
              "type": "object",
              "properties": {
                "UpThreshold": {
                  "$ref": "#/$defs/ubyte",
                  "description": "NBFC will select the next upper threshold as soon as the temperature exceeds *UpThreshold*. in celsius"
                },
                "DownThreshold": {
                  "$ref": "#/$defs/ubyte",
                  "description": "NBFC will select the next lower threshold as soon as the temperature falls below the *DownThreshold*. in celsius"
                },
                "FanSpeed": {
                  "$ref": "#/$defs/percentage",
                  "description": "The fan speed in percent"
                }
              },
              "required": ["UpThreshold", "DownThreshold", "FanSpeed"]
            }
          },
          "FanSpeedPercentageOverrides": {
            "type": "array",
            "description": "Overrides the default algorithm to calculate fan speeds",
            "items": {
              "type": "object",
              "properties": {
                "FanSpeedPercentage": {
                  "$ref": "#/$defs/percentage",
                  "description": "The fan speed in percent"
                },
                "FanSpeedValue": {
                  "$ref": "#/$defs/uword",
                  "description": "Fan speed value which will be written to WriteRegister"
                },
                "TargetOperation": {
                  "type": "string",
                  "default": "ReadWrite",
                  "anyOf": [
                    {
                      "const": "Read",
                      "description": "Value->Percentage"
                    },
                    {
                      "const": "Write",
                      "description": "Percentage->Value"
                    },
                    {
                      "const": "ReadWrite",
                      "description": "both"
                    }
                  ],
                  "description": "Defines for which operations the speeds should be overridden."
                }
              }
            }
          }
        },
        "required": [
          "ReadRegister",
          "WriteRegister",
          "MinSpeedValue",
          "MaxSpeedValue",
          "IndependentReadMinMaxValues",
          "MinSpeedValueRead",
          "MaxSpeedValueRead",
          "ResetRequired",
          "FanSpeedResetValue",
          "FanDisplayName",
          "TemperatureThresholds",
          "FanSpeedPercentageOverrides"
        ]
      }
    },
    "RegisterWriteConfigurations": {
      "type": "array",
      "description": "Allows to write to any EC register",
      "items": {
        "type": "object",
        "properties": {
          "WriteMode": {
            "$ref": "#/$defs/writeModeDef",
            "description": "Defines how the value will be written"
          },
          "WriteOccasion": {
            "type": "string",
            "description": "Defines when the value should be written",
            "default": "OnInitialization",
            "anyOf": [
              {
                "const": "OnInitialization",
                "description": "writes the value once upon initialization (everytime the fan control service is enabled or a config is applied)"
              },
              {
                "const": "OnWriteFanSpeed",
                "description": "writes the value everytime the fan speed is set."
              }
            ]
          },
          "Register": {
            "$ref": "#/$defs/ubyte",
            "description": "The register which will be manipulated."
          },
          "Value": {
            "$ref": "#/$defs/uword",
            "description": "The Value which will be written"
          },
          "ResetRequired": {
            "type": "boolean",
            "description": "Defines if the register should be reset before the service is shut down.",
            "enum": [true, false],
            "default": false
          },
          "ResetValue": {
            "$ref": "#/$defs/uword",
            "description": "The value which will be written upon reset."
          },
          "ResetWriteMode": {
            "$ref": "#/$defs/writeModeDef",
            "description": "See WriteMode. Will only be applied on reset"
          },
          "Description": {
            "type": "string",
            "description": "A description of what effect the RegisterWriteConfiguration will have",
            "default": ""
          }
        },
        "required": [
          "WriteMode",
          "WriteOccasion",
          "Register",
          "Value",
          "ResetRequired",
          "ResetValue",
          "ResetWriteMode",
          "Description"
        ]
      }
    }
  },
  "required": [
    "NotebookModel",
    "Author",
    "EcPollInterval",
    "ReadWriteWords",
    "CriticalTemperature",
    "FanConfigurations",
    "RegisterWriteConfigurations"
  ],
  "$defs": {
    "writeModeDef": {
      "type": "string",
      "default": "Set",
      "anyOf": [
        {
          "const": "And",
          "description": "register = register bitwise_and value"
        },
        {
          "const": "Or",
          "description": "register = register bitwise_or value"
        },
        {
          "const": "Set",
          "description": "register = value"
        }
      ]
    },
    "ubyte": {
      "type": "integer",
      "minimum": 0,
      "maximum": 255
    },
    "percentage": {
      "type": "number",
      "minimum": 0.0,
      "maximum": 100.0
    },
    "uword": {
      "type": "integer",
      "minimum": 0,
      "maximum": 65535
    }
  }
}

=== nbfc-linux/nbfc-linux/AppDirPPDIR/share/nbfc/configs/Asus G53SX.json
{
 "NotebookModel": "G53SX",
 "Author": "flexbrane",
 "EcPollInterval": 300,
 "ReadWriteWords": false,
 "CriticalTemperature": 85,
 "FanConfigurations": [
	{
	 "ReadRegister": 152,
	 "WriteRegister": 152,
	 "MinSpeedValue": 0,
	 "MaxSpeedValue": 7,
	 "IndependentReadMinMaxValues": false,
	 "MinSpeedValueRead": 0,
	 "MaxSpeedValueRead": 0,
	 "ResetRequired": true,
	 "FanSpeedResetValue": 1,
	 "FanDisplayName": "CPU",
	 "TemperatureThresholds": [
	  {
	   "UpThreshold": 55,
	   "DownThreshold": 0,
	   "FanSpeed": 0.0
	  },
	  {
	   "UpThreshold": 60,
	   "DownThreshold": 50,
	   "FanSpeed": 14.2857151
	  },
	  {
	   "UpThreshold": 65,
	   "DownThreshold": 55,
	   "FanSpeed": 28.57143
	  },
	  {
	   "UpThreshold": 70,
	   "DownThreshold": 55,
	   "FanSpeed": 42.8571434
	  },
	  {
	   "UpThreshold": 75,
	   "DownThreshold": 60,
	   "FanSpeed": 71.42857
	  },
	  {
	   "UpThreshold": 80,
	   "DownThreshold": 65,
	   "FanSpeed": 85.71429
	  },
	  {
	   "UpThreshold": 85,
	   "DownThreshold": 70,
	   "FanSpeed": 100.0
	  }
	 ],
	 "FanSpeedPercentageOverrides": []
	},
	{
	 "ReadRegister": 151,
	 "WriteRegister": 151,
	 "MinSpeedValue": 0,
	 "MaxSpeedValue": 6,
	 "IndependentReadMinMaxValues": false,
	 "MinSpeedValueRead": 0,
	 "MaxSpeedValueRead": 0,
	 "ResetRequired": true,
	 "FanSpeedResetValue": 1,
	 "FanDisplayName": "GPU",
	 "TemperatureThresholds": [
	  {
	   "UpThreshold": 60,
	   "DownThreshold": 0,
	   "FanSpeed": 0.0
	  },
	  {
	   "UpThreshold": 65,
	   "DownThreshold": 55,
	   "FanSpeed": 16.6666679
	  },
	  {
	   "UpThreshold": 70,
	   "DownThreshold": 55,
	   "FanSpeed": 16.6666679
	  },
	  {
	   "UpThreshold": 75,
	   "DownThreshold": 60,
	   "FanSpeed": 33.3333359
	  },
	  {
	   "UpThreshold": 80,
	   "DownThreshold": 65,
	   "FanSpeed": 50.0
	  },
	  {
	   "UpThreshold": 85,
	   "DownThreshold": 70,
	   "FanSpeed": 66.66667
	  },
	  {
	   "UpThreshold": 85,
	   "DownThreshold": 65,
	   "FanSpeed": 100.0
	  }
	 ],
	 "FanSpeedPercentageOverrides": []
	}
 ],
 "RegisterWriteConfigurations": []
}

=== nbfc-linux/nbfc-linux/AppDirPPDIR/share/nbfc/configs/Lenovo Ideapad 710S.json
{
 "NotebookModel": "Ideapad 710S",
 "Author": "Florian Melsheimer",
 "EcPollInterval": 750,
 "ReadWriteWords": false,
 "CriticalTemperature": 92,
 "FanConfigurations": [
	{
	 "ReadRegister": 149,
	 "WriteRegister": 148,
	 "MinSpeedValue": 255,
	 "MaxSpeedValue": 72,
	 "IndependentReadMinMaxValues": false,
	 "MinSpeedValueRead": 0,
	 "MaxSpeedValueRead": 0,
	 "ResetRequired": true,
	 "FanSpeedResetValue": 72,
	 "FanDisplayName": "Fan #1",
	 "TemperatureThresholds": [
	  {
	   "UpThreshold": 55,
	   "DownThreshold": 0,
	   "FanSpeed": 0.0
	  },
	  {
	   "UpThreshold": 65,
	   "DownThreshold": 50,
	   "FanSpeed": 20.765028
	  },
	  {
	   "UpThreshold": 75,
	   "DownThreshold": 60,
	   "FanSpeed": 50.81967
	  },
	  {
	   "UpThreshold": 85,
	   "DownThreshold": 70,
	   "FanSpeed": 75.4098358
	  },
	  {
	   "UpThreshold": 92,
	   "DownThreshold": 80,
	   "FanSpeed": 100.0
	  }
	 ],
	 "FanSpeedPercentageOverrides": []
	},
	{
	 "ReadRegister": 152,
	 "WriteRegister": 151,
	 "MinSpeedValue": 255,
	 "MaxSpeedValue": 72,
	 "IndependentReadMinMaxValues": false,
	 "MinSpeedValueRead": 0,
	 "MaxSpeedValueRead": 0,
	 "ResetRequired": true,
	 "FanSpeedResetValue": 72,
	 "FanDisplayName": "Fan #2",
	 "TemperatureThresholds": [
	  {
	   "UpThreshold": 57,
	   "DownThreshold": 0,
	   "FanSpeed": 0.0
	  },
	  {
	   "UpThreshold": 67,
	   "DownThreshold": 52,
	   "FanSpeed": 20.21858
	  },
	  {
	   "UpThreshold": 77,
	   "DownThreshold": 62,
	   "FanSpeed": 50.81967
	  },
	  {
	   "UpThreshold": 83,
	   "DownThreshold": 72,
	   "FanSpeed": 74.86339
	  },
	  {
	   "UpThreshold": 92,
	   "DownThreshold": 77,
	   "FanSpeed": 100.0
	  }
	 ],
	 "FanSpeedPercentageOverrides": []
	}
 ],
 "RegisterWriteConfigurations": [
	{
	 "WriteMode": "Set",
	 "WriteOccasion": "OnInitialization",
	 "Register": 147,
	 "Value": 20,
	 "ResetRequired": true,
	 "ResetValue": 4,
	 "ResetWriteMode": "Set",
	 "Description": "Enable manual EC control"
	},
	{
	 "WriteMode": "Set",
	 "WriteOccasion": "OnInitialization",
	 "Register": 150,
	 "Value": 20,
	 "ResetRequired": true,
	 "ResetValue": 4,
	 "ResetWriteMode": "Set",
	 "Description": "Enable manual EC control"
	}
 ]
}

=== nbfc-linux/nbfc-linux/AppDirPPDIR/share/nbfc/configs/HP Notebook 15-ba010ng.json
{
 "NotebookModel": "HP Notebook 15-ba010ng",
 "Author": "Webloft",
 "EcPollInterval": 750,
 "ReadWriteWords": false,
 "CriticalTemperature": 85,
 "FanConfigurations": [
	{
	 "ReadRegister": 17,
	 "WriteRegister": 25,
	 "MinSpeedValue": 3,
	 "MaxSpeedValue": 54,
	 "IndependentReadMinMaxValues": true,
	 "MinSpeedValueRead": 5,
	 "MaxSpeedValueRead": 62,
	 "ResetRequired": false,
	 "FanSpeedResetValue": 0,
	 "FanDisplayName": "Main Fan",
	 "TemperatureThresholds": [],
	 "FanSpeedPercentageOverrides": []
	}
 ],
 "RegisterWriteConfigurations": [
	{
	 "WriteMode": "Set",
	 "WriteOccasion": "OnInitialization",
	 "Register": 21,
	 "Value": 1,
	 "ResetRequired": true,
	 "ResetValue": 0,
	 "ResetWriteMode": "Set",
	 "Description": "Manual Override"
	}
 ]
}

=== nbfc-linux/nbfc-linux/share/nbfc/configs/HP EliteBook 850 G5.json
{
 "LegacyTemperatureThresholdsBehaviour": true,
 "NotebookModel": "HP EliteBook 850 G5",
 "EcPollInterval": 2000,
 "ReadWriteWords": false,
 "CriticalTemperature": 78,
 "Author": "pustotnik",
 "FanConfigurations": [
	{
	 "ReadRegister": 46,
	 "WriteRegister": 47,
	 "MinSpeedValue": 255,
	 "MaxSpeedValue": 40,
	 "IndependentReadMinMaxValues": false,
	 "MinSpeedValueRead": 0,
	 "MaxSpeedValueRead": 0,
	 "ResetRequired": true,
	 "FanSpeedResetValue": 255,
	 "FanDisplayName": "CPU fan",
	 "TemperatureThresholds": [
	  {
	   "UpThreshold": 0,
	   "DownThreshold": 0,
	   "FanSpeed": 0.0
	  },
	  {
	   "UpThreshold": 50,
	   "DownThreshold": 45,
	   "FanSpeed": 30.0
	  },
	  {
	   "UpThreshold": 55,
	   "DownThreshold": 48,
	   "FanSpeed": 60.0
	  },
	  {
	   "UpThreshold": 60,
	   "DownThreshold": 50,
	   "FanSpeed": 70.0
	  },
	  {
	   "UpThreshold": 63,
	   "DownThreshold": 56,
	   "FanSpeed": 78.0
	  },
	  {
	   "UpThreshold": 65,
	   "DownThreshold": 60,
	   "FanSpeed": 88.0
	  },
	  {
	   "UpThreshold": 68,
	   "DownThreshold": 62,
	   "FanSpeed": 90.0
	  },
	  {
	   "UpThreshold": 70,
	   "DownThreshold": 66,
	   "FanSpeed": 96.0
	  }
	 ],
	 "FanSpeedPercentageOverrides": [
	  {
	   "FanSpeedPercentage": 0.0,
	   "FanSpeedValue": 255,
	   "TargetOperation": "ReadWrite"
	  }
	 ]
	}
 ],
 "RegisterWriteConfigurations": [
	{
	 "WriteMode": "Set",
	 "WriteOccasion": "OnInitialization",
	 "Register": 34,
	 "Value": 1,
	 "ResetRequired": true,
	 "ResetValue": 1,
	 "ResetWriteMode": "Set",
	 "Description": "Select thermal zone"
	},
	{
	 "WriteMode": "Set",
	 "WriteOccasion": "OnInitialization",
	 "Register": 38,
	 "Value": 28,
	 "ResetRequired": true,
	 "ResetValue": 0,
	 "ResetWriteMode": "Set",
	 "Description": "Fake thermal zone temperature"
	}
 ]
}

=== nbfc-linux/nbfc-linux/share/nbfc/configs/HP EliteBook Folio 1040 G1.json
{
 "LegacyTemperatureThresholdsBehaviour": true,
 "NotebookModel": "HP EliteBook Folio 1040 G1",
 "Author": "Daniel Andersen",
 "EcPollInterval": 3000,
 "ReadWriteWords": false,
 "CriticalTemperature": 90,
 "FanConfigurations": [
	{
	 "ReadRegister": 46,
	 "WriteRegister": 47,
	 "MinSpeedValue": 90,
	 "MaxSpeedValue": 34,
	 "IndependentReadMinMaxValues": false,
	 "MinSpeedValueRead": 0,
	 "MaxSpeedValueRead": 0,
	 "ResetRequired": true,
	 "FanSpeedResetValue": 255,
	 "FanDisplayName": "CPU Fan",
	 "TemperatureThresholds": [
	  {
	   "UpThreshold": 0,
	   "DownThreshold": 0,
	   "FanSpeed": 0.0
	  },
	  {
	   "UpThreshold": 60,
	   "DownThreshold": 48,
	   "FanSpeed": 10.0
	  },
	  {
	   "UpThreshold": 63,
	   "DownThreshold": 55,
	   "FanSpeed": 20.0
	  },
	  {
	   "UpThreshold": 66,
	   "DownThreshold": 59,
	   "FanSpeed": 50.0
	  },
	  {
	   "UpThreshold": 68,
	   "DownThreshold": 63,
	   "FanSpeed": 70.0
	  },
	  {
	   "UpThreshold": 71,
	   "DownThreshold": 67,
	   "FanSpeed": 100.0
	  }
	 ],
	 "FanSpeedPercentageOverrides": [
	  {
	   "FanSpeedPercentage": 0.0,
	   "FanSpeedValue": 255,
	   "TargetOperation": "ReadWrite"
	  }
	 ]
	}
 ],
 "RegisterWriteConfigurations": [
	{
	 "WriteMode": "Set",
	 "WriteOccasion": "OnInitialization",
	 "Register": 34,
	 "Value": 1,
	 "ResetRequired": true,
	 "ResetValue": 1,
	 "ResetWriteMode": "Set",
	 "Description": "Select thermal zone"
	},
	{
	 "WriteMode": "Set",
	 "WriteOccasion": "OnInitialization",
	 "Register": 38,
	 "Value": 28,
	 "ResetRequired": true,
	 "ResetValue": 0,
	 "ResetWriteMode": "Set",
	 "Description": "Fake thermal zone temperature"
	}
 ]
}

=== nbfc-linux/nbfc-linux/share/nbfc/configs/HP ENVY m6-1254eo.json
{
 "LegacyTemperatureThresholdsBehaviour": true,
 "NotebookModel": "HP ENVY m6-1254eo Notebook PC",
 "Author": "Brian Nelson",
 "EcPollInterval": 1000,
 "ReadWriteWords": false,
 "CriticalTemperature": 85,
 "FanConfigurations": [
	{
	 "ReadRegister": 17,
	 "WriteRegister": 20,
	 "MinSpeedValue": 30,
	 "MaxSpeedValue": 68,
	 "IndependentReadMinMaxValues": false,
	 "MinSpeedValueRead": 0,
	 "MaxSpeedValueRead": 0,
	 "ResetRequired": false,
	 "FanSpeedResetValue": 0,
	 "FanDisplayName": "CPU Fan",
	 "TemperatureThresholds": [
	  {
	   "UpThreshold": 50,
	   "DownThreshold": 40,
	   "FanSpeed": 25.0
	  },
	  {
	   "UpThreshold": 80,
	   "DownThreshold": 70,
	   "FanSpeed": 100.0
	  },
	  {
	   "UpThreshold": 40,
	   "DownThreshold": 30,
	   "FanSpeed": 20.0
	  },
	  {
	   "UpThreshold": 20,
	   "DownThreshold": 0,
	   "FanSpeed": 10.0
	  },
	  {
	   "UpThreshold": 70,
	   "DownThreshold": 60,
	   "FanSpeed": 77.5
	  },
	  {
	   "UpThreshold": 60,
	   "DownThreshold": 50,
	   "FanSpeed": 47.5
	  }
	 ],
	 "FanSpeedPercentageOverrides": [
	  {
	   "FanSpeedPercentage": 76.92308,
	   "FanSpeedValue": 39,
	   "TargetOperation": "ReadWrite"
	  },
	  {
	   "FanSpeedPercentage": 38.46154,
	   "FanSpeedValue": 34,
	   "TargetOperation": "ReadWrite"
	  }
	 ]
	}
 ],
 "RegisterWriteConfigurations": [
	{
	 "WriteMode": "Or",
	 "WriteOccasion": "OnInitialization",
	 "Register": 15,
	 "Value": 8,
	 "ResetRequired": true,
	 "ResetValue": 5,
	 "ResetWriteMode": "Set",
	 "Description": "Manual Override"
	}
 ]
}

=== nbfc-linux/nbfc-linux/AppDirPPDIR/share/nbfc/configs/HP ProBook 6550b.json
{
 "NotebookModel": "HP ProBook 6550b",
 "Author": "djbozkosz",
 "EcPollInterval": 500,
 "ReadWriteWords": false,
 "CriticalTemperature": 80,
 "FanConfigurations": [
	{
	 "ReadRegister": 215,
	 "WriteRegister": 214,
	 "MinSpeedValue": 30,
	 "MaxSpeedValue": 100,
	 "IndependentReadMinMaxValues": false,
	 "MinSpeedValueRead": 0,
	 "MaxSpeedValueRead": 0,
	 "ResetRequired": false,
	 "FanSpeedResetValue": 20,
	 "FanDisplayName": "CPU Fan",
	 "TemperatureThresholds": [
	  {
	   "UpThreshold": 40,
	   "DownThreshold": 0,
	   "FanSpeed": 0.0
	  },
	  {
	   "UpThreshold": 45,
	   "DownThreshold": 35,
	   "FanSpeed": 30.0
	  },
	  {
	   "UpThreshold": 50,
	   "DownThreshold": 40,
	   "FanSpeed": 50.0
	  },
	  {
	   "UpThreshold": 55,
	   "DownThreshold": 45,
	   "FanSpeed": 80.0
	  },
	  {
	   "UpThreshold": 80,
	   "DownThreshold": 50,
	   "FanSpeed": 100.0
	  }
	 ],
	 "FanSpeedPercentageOverrides": []
	}
 ],
 "RegisterWriteConfigurations": []
}

=== nbfc-linux/nbfc-linux/AppDirPPDIR/share/nbfc/configs/HP OMEN Notebook PC 15.json
{
 "NotebookModel": "HP OMEN 5001NG",
 "Author": "Eberh@rd",
 "EcPollInterval": 2222,
 "ReadWriteWords": false,
 "CriticalTemperature": 80,
 "FanConfigurations": [
	{
	 "ReadRegister": 149,
	 "WriteRegister": 148,
	 "MinSpeedValue": 255,
	 "MaxSpeedValue": 58,
	 "IndependentReadMinMaxValues": false,
	 "MinSpeedValueRead": 0,
	 "MaxSpeedValueRead": 0,
	 "ResetRequired": false,
	 "FanSpeedResetValue": 89,
	 "FanDisplayName": "CPU fan",
	 "TemperatureThresholds": [
	  {
	   "UpThreshold": 70,
	   "DownThreshold": 0,
	   "FanSpeed": 0.0
	  },
	  {
	   "UpThreshold": 75,
	   "DownThreshold": 56,
	   "FanSpeed": 10.0
	  },
	  {
	   "UpThreshold": 76,
	   "DownThreshold": 65,
	   "FanSpeed": 20.0
	  },
	  {
	   "UpThreshold": 77,
	   "DownThreshold": 66,
	   "FanSpeed": 30.0
	  },
	  {
	   "UpThreshold": 78,
	   "DownThreshold": 67,
	   "FanSpeed": 50.0
	  },
	  {
	   "UpThreshold": 80,
	   "DownThreshold": 68,
	   "FanSpeed": 100.0
	  }
	 ],
	 "FanSpeedPercentageOverrides": []
	}
 ],
 "RegisterWriteConfigurations": [
	{
	 "WriteMode": "Set",
	 "WriteOccasion": "OnInitialization",
	 "Register": 147,
	 "Value": 20,
	 "ResetRequired": true,
	 "ResetValue": 4,
	 "ResetWriteMode": "Set",
	 "Description": "CPU fan init"
	}
 ]
}
